# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Frauen Lesekreise
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
 "Hallo liebe Freunde und herzlich willkommen zum Frauen Lesekreise! Wir haben diesen Club ins Leben gerufen, um unsere Deutschkenntnisse zu verbessern und uns mit anderen Frauen aus deutschsprachigen Ländern über etwas auszutauschen, das wir alle lieben: Bücher. Jeden Monat werden wir einen neuen Titel ankündigen, den wir alle lesen werden, ausgewählt von uns."
logo: "/images/logo.jpeg"
read_time: false
paginate: 10
paginate_path: /page:num/
baseurl: "/deutschlesekreise" # the subpath of your site, e.g. /blog
url: "https://zehrahayirci.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
#theme : minima
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  homemade:
    output: true
    permalink: /:collection/:path/
  coffee:
    output: true
    permalink: /:collection/:path/
    
# Front Matter Defaults
defaults:
  # Recipe defaults
  - scope:
      path: "_homemade"
      type: homemade
    values:
      layout: post
      comments: false
      share: true
   # Coffee defaults
  - scope:
      path: "_coffee"
      type: Archive
    values:
      layout: post
      comments: true
      share: true  
